### ISSUE TITLE
Execution error with example

### ISSUE THREAD

**Issue by patrick-compass** [23maverick23/oaxmlapi#22]
Windows 10
Python 2.7.16

```python
Traceback (most recent call last):
  File "C:\ProjectsGit\open-air\example.py", line 14, in <module>
    xml_data.append(commands.Read('Task', 'equal to', {'limit': '1000'}, [filter1, filter2], ['id', 'timesheetid']).read())
  File "C:\Python27\lib\site-packages\oaxmlapi-1.1.1-py2.7.egg\oaxmlapi\commands.py", line 118, in read
    field = self.orderby.get('field', 'id')
AttributeError: 'list' object has no attribute 'get'

**Comment by 23maverick23** [comment]
The example in the README was never updated to include the new `orderby` attribute for the `Read` method. Please read the documentation for more details.
https://23maverick23.gitbook.io/oaxmlapi/docs/commands#read
